site_name: HR Server Docs
site_description: Minimal docs for hr-server development and deployment

theme:
  name: material
  features:
    - content.code.copy
    - navigation.top

plugins:
  - search

nav:
  - Home: index.md
  - Development: development-minimal-zh.md
  - Deployment: deployment-zh.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
