MAIL_SIGNATURE_NAME_MAX_LENGTH = 120
MAIL_SIGNATURE_TEAM_MAX_LENGTH = 120
MAIL_SIGNATURE_FULL_NAME_MAX_LENGTH = 120
MAIL_SIGNATURE_JOB_TITLE_MAX_LENGTH = 120
MAIL_SIGNATURE_COMPANY_NAME_MAX_LENGTH = 120
MAIL_SIGNATURE_EMAIL_MAX_LENGTH = 255
MAIL_SIGNATURE_URL_MAX_LENGTH = 500
MAIL_SIGNATURE_LINKEDIN_LABEL_MAX_LENGTH = 255
MAIL_SIGNATURE_ADDRESS_MAX_LENGTH = 500

