from collections.abc import Callable
from typing import Any

from ..app.core.exceptions.http_exceptions import NotFoundException
from .v2.shared import build_minimal_pdf_bytes


def build_demo_resume_pdf_bytes(*, email: str, generated_by: str) -> bytes:
    return build_minimal_pdf_bytes(f"Demo resume for {email}. Generated by {generated_by}.")


def is_valid_pdf_bytes(content: bytes) -> bool:
    return content.startswith(b"%PDF-") and content.rstrip().endswith(b"%%EOF")


def refresh_demo_resume_asset_if_needed(
    asset: Any,
    *,
    email: str,
    generated_by: str,
    read_content: Callable[[Any], bytes],
    store_content: Callable[..., None],
) -> bool:
    try:
        current_content = read_content(asset)
    except NotFoundException:
        current_content = b""
    if is_valid_pdf_bytes(current_content):
        return False

    content = build_demo_resume_pdf_bytes(email=email, generated_by=generated_by)
    store_content(storage_key=asset.storage_key, content=content, mime_type="application/pdf")
    asset.mime_type = "application/pdf"
    asset.file_size = len(content)
    next_data = dict(asset.data or {})
    next_data["generated_by"] = generated_by
    next_data["regenerated_pdf"] = True
    asset.data = next_data
    return True
