import argparse
import asyncio
import json
from pathlib import Path
from typing import Any
from uuid import uuid4

import httpx
from sqlalchemy import or_, select

from ..app.core.db.database import async_engine, local_session
from ..app.modules.assets.model import Asset
from ..app.modules.assets.service import get_asset_storage_root
from ..app.modules.candidate_field.const import CandidateFieldKey
from ..app.modules.user.model import User

DEFAULT_BASE_URL = "http://127.0.0.1:8000/api/v1"
DEFAULT_NAME = "Demo Candidate"
DEFAULT_EMAIL = "demo.candidate@example.com"
DEFAULT_PASSWORD = "Candidate123!"
DEFAULT_JOB_TITLES = [
    "Portuguese Data Annotator Demo",
    "Brazil Language QA Reviewer Demo",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Register a demo candidate and apply to seeded jobs.")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="Web API base URL.")
    parser.add_argument("--name", default=DEFAULT_NAME, help="Candidate name.")
    parser.add_argument("--email", default=DEFAULT_EMAIL, help="Candidate email.")
    parser.add_argument("--password", default=DEFAULT_PASSWORD, help="Candidate password.")
    parser.add_argument(
        "--job-id",
        action="append",
        type=int,
        dest="job_ids",
        help="Apply to a specific job id. Can be repeated.",
    )
    return parser.parse_args()


async def register_or_reuse_candidate(
    client: httpx.AsyncClient,
    *,
    name: str,
    email: str,
    password: str,
) -> dict[str, Any]:
    response = await client.post(
        "/user/register",
        json={
            "name": name,
            "email": email,
            "password": password,
        },
    )
    if response.status_code == 201:
        payload = response.json()
        print(f"[register] created candidate user id={payload['id']} username={payload['username']}")
        return payload

    if response.status_code == 422:
        detail = response.json().get("detail")
        if detail == "Email is already registered":
            print(f"[register] candidate {email} already exists, continue with login")
            return {}

    raise RuntimeError(f"Failed to register candidate: {response.status_code} {response.text}")


async def login_candidate(
    client: httpx.AsyncClient,
    *,
    email: str,
    password: str,
) -> str:
    response = await client.post(
        "/login",
        data={"username": email, "password": password},
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    if response.status_code != 200:
        raise RuntimeError(f"Failed to login candidate: {response.status_code} {response.text}")
    access_token = response.json()["access_token"]
    print("[login] candidate login succeeded")
    return access_token


async def fetch_current_user(
    client: httpx.AsyncClient,
    *,
    access_token: str,
) -> dict[str, Any]:
    response = await client.get(
        "/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    if response.status_code != 200:
        raise RuntimeError(f"Failed to fetch current user: {response.status_code} {response.text}")
    payload = response.json()
    print(f"[me] user id={payload['id']} username={payload['username']} email={payload['email']}")
    return payload


async def ensure_resume_asset(*, user_id: int, email: str) -> Asset:
    async with local_session() as session:
        result = await session.execute(
            select(Asset).where(
                Asset.owner_type == "user",
                Asset.owner_id == user_id,
                Asset.module == "candidate",
                Asset.type == "file",
                Asset.original_name == "demo-resume.pdf",
                Asset.is_deleted.is_(False),
            )
        )
        existing = result.scalar_one_or_none()
        if existing is not None:
            print(f"[resume] reuse asset id={existing.id}")
            return existing

        storage_key = f"candidate/file/{uuid4().hex}-demo-resume.pdf"
        root = get_asset_storage_root()
        path = root / storage_key
        path.parent.mkdir(parents=True, exist_ok=True)
        content = (
            f"Demo resume for {email}\n"
            "This file is generated by run_client_apply_demo.py for apply flow verification.\n"
        ).encode("utf-8")
        path.write_bytes(content)

        asset = Asset(
            type="file",
            module="candidate",
            owner_type="user",
            owner_id=user_id,
            original_name="demo-resume.pdf",
            storage_key=storage_key,
            mime_type="application/pdf",
            file_size=len(content),
            data={"generated_by": "run_client_apply_demo"},
        )
        session.add(asset)
        await session.commit()
        await session.refresh(asset)
        print(f"[resume] created asset id={asset.id}")
        return asset


async def resolve_job_ids(client: httpx.AsyncClient, *, requested_ids: list[int] | None) -> list[int]:
    if requested_ids:
        return requested_ids

    response = await client.get("/jobs")
    if response.status_code != 200:
        raise RuntimeError(f"Failed to list jobs: {response.status_code} {response.text}")
    items = response.json().get("items", [])
    matched_ids: list[int] = []
    for title in DEFAULT_JOB_TITLES:
        matched = next((item for item in items if item.get("title") == title), None)
        if matched is None:
            raise RuntimeError(f"Could not find seeded job titled: {title}")
        matched_ids.append(int(matched["id"]))
    print(f"[jobs] resolved demo jobs {matched_ids}")
    return matched_ids


def build_application_items(
    *,
    job_index: int,
    candidate_name: str,
    email: str,
    resume_asset_id: int,
) -> list[dict[str, Any]]:
    if job_index == 0:
        whatsapp = "+55 11 90000 0001"
        nationality = "Brazilian"
        country_of_residence = "Brazil"
        education_status = "bachelor_completed"
        native_languages = "Portuguese"
        additional_languages = "English"
        age_range = "26_30"
        max_working_hours = "4_8_hours"
        accepts_hourly_payment = "yes"
        expected_salary = "2_5"
        ai_annotation_experience = "0_3_months"
        visa_requirement = "no_sponsorship_required"
        job_source = "linkedin_job_post"
        additional_information = "Initial apply flow demo submission."
    else:
        whatsapp = "+55 11 90000 0002"
        nationality = "Brazilian"
        country_of_residence = "Brazil"
        education_status = "master_completed"
        native_languages = "Portuguese"
        additional_languages = "English, Spanish"
        age_range = "31_35"
        max_working_hours = "over_8_hours"
        accepts_hourly_payment = "yes"
        expected_salary = "6_10"
        ai_annotation_experience = "1_2_years"
        visa_requirement = "no_sponsorship_required"
        job_source = "indeed_job_post"
        additional_information = "Second submission prepared for manual merge verification."

    return [
        {"field_key": CandidateFieldKey.FULL_NAME.value, "value": candidate_name},
        {"field_key": CandidateFieldKey.EMAIL.value, "value": email},
        {"field_key": CandidateFieldKey.WHATSAPP.value, "value": whatsapp},
        {"field_key": CandidateFieldKey.COUNTRY_OF_RESIDENCE.value, "value": country_of_residence},
        {"field_key": CandidateFieldKey.NATIONALITY.value, "value": nationality},
        {"field_key": CandidateFieldKey.NATIVE_LANGUAGES.value, "value": native_languages},
        {"field_key": CandidateFieldKey.ADDITIONAL_LANGUAGES.value, "value": additional_languages},
        {"field_key": CandidateFieldKey.AGE_RANGE.value, "value": age_range, "display_value": age_range},
        {
            "field_key": CandidateFieldKey.MAX_WORKING_HOURS_PER_DAY.value,
            "value": max_working_hours,
            "display_value": max_working_hours,
        },
        {
            "field_key": CandidateFieldKey.ACCEPTS_HOURLY_PAYMENT.value,
            "value": accepts_hourly_payment,
            "display_value": accepts_hourly_payment,
        },
        {
            "field_key": CandidateFieldKey.EXPECTED_SALARY_USD_PER_HOUR.value,
            "value": expected_salary,
            "display_value": expected_salary,
        },
        {
            "field_key": CandidateFieldKey.EDUCATION_STATUS.value,
            "value": education_status,
            "display_value": education_status,
        },
        {
            "field_key": CandidateFieldKey.AI_DATA_ANNOTATION_EXPERIENCE.value,
            "value": ai_annotation_experience,
            "display_value": ai_annotation_experience,
        },
        {
            "field_key": CandidateFieldKey.REQUIRES_VISA_SPONSORSHIP.value,
            "value": visa_requirement,
            "display_value": visa_requirement,
        },
        {
            "field_key": CandidateFieldKey.RESUME_ATTACHMENT.value,
            "value": "demo-resume.pdf",
            "display_value": "demo-resume.pdf",
            "asset_id": resume_asset_id,
        },
        {
            "field_key": CandidateFieldKey.JOB_SOURCE.value,
            "value": job_source,
            "display_value": job_source,
        },
        {
            "field_key": CandidateFieldKey.ADDITIONAL_INFORMATION.value,
            "value": additional_information,
        },
    ]


async def submit_application(
    client: httpx.AsyncClient,
    *,
    access_token: str,
    job_id: int,
    items: list[dict[str, Any]],
) -> dict[str, Any]:
    response = await client.post(
        f"/jobs/{job_id}/apply",
        headers={"Authorization": f"Bearer {access_token}"},
        json={"items": items},
    )
    if response.status_code != 200:
        raise RuntimeError(f"Failed to apply job {job_id}: {response.status_code} {response.text}")
    payload = response.json()
    print(
        "[apply] job_id={job_id} application_id={application_id} talent_profile_id={talent_profile_id} "
        "talent_profile_created={talent_profile_created} auto_merged={auto_merged}".format(**payload, job_id=job_id)
    )
    return payload


async def fetch_job_detail(client: httpx.AsyncClient, *, job_id: int) -> dict[str, Any]:
    response = await client.get(f"/jobs/{job_id}")
    if response.status_code != 200:
        raise RuntimeError(f"Failed to fetch job detail {job_id}: {response.status_code} {response.text}")
    payload = response.json()
    print(f"[job] {job_id} title={payload['title']} form_template_id={payload['form_template_id']} fields={len(payload['form_fields'])}")
    return payload


async def main() -> None:
    args = parse_args()
    try:
        async with httpx.AsyncClient(base_url=args.base_url.rstrip("/"), timeout=30.0) as client:
            await register_or_reuse_candidate(
                client,
                name=args.name,
                email=args.email,
                password=args.password,
            )
            access_token = await login_candidate(client, email=args.email, password=args.password)
            current_user = await fetch_current_user(client, access_token=access_token)
            resume_asset = await ensure_resume_asset(user_id=int(current_user["id"]), email=args.email)

            job_ids = await resolve_job_ids(client, requested_ids=args.job_ids)
            applications: list[dict[str, Any]] = []
            for index, job_id in enumerate(job_ids):
                await fetch_job_detail(client, job_id=job_id)
                items = build_application_items(
                    job_index=index,
                    candidate_name=args.name,
                    email=args.email,
                    resume_asset_id=resume_asset.id,
                )
                applications.append(
                    await submit_application(
                        client,
                        access_token=access_token,
                        job_id=job_id,
                        items=items,
                    )
                )

            summary = {
                "candidate": {
                    "id": current_user["id"],
                    "name": current_user["name"],
                    "username": current_user["username"],
                    "email": current_user["email"],
                },
                "resume_asset_id": resume_asset.id,
                "job_ids": job_ids,
                "applications": applications,
            }
            print(json.dumps(summary, ensure_ascii=False, indent=2))
    finally:
        await async_engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
