import argparse
import asyncio
from typing import Any

import httpx
from sqlalchemy import select

from ..app.core.db.database import local_session
from ..app.modules.job_progress.const import RecruitmentStage
from ..app.modules.job_progress.model import JobProgress
from ..app.modules.user.model import User
from .run_client_assessment_upload_demo import build_demo_pdf_bytes, login_candidate

DEFAULT_BASE_URL = "http://127.0.0.1:8000/api/v1"
DEFAULT_EMAIL = "qq712696307@gmail.com"
DEFAULT_PASSWORD = "Candidate123!"
DEFAULT_FILE_NAME = "candidate-signed-contract.pdf"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Upload a demo candidate signed contract as a candidate user.")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="Web API base URL.")
    parser.add_argument("--email", default=DEFAULT_EMAIL, help="Candidate email.")
    parser.add_argument("--password", default=DEFAULT_PASSWORD, help="Candidate password.")
    parser.add_argument("--job-id", type=int, default=None, help="Target job id. Defaults to latest contract pool record.")
    parser.add_argument("--file-name", default=DEFAULT_FILE_NAME, help="Uploaded file name.")
    parser.add_argument(
        "--note",
        default="This signed contract attachment is generated by run_client_signed_contract_upload_demo.py.",
        help="Short note rendered into the demo PDF body.",
    )
    return parser.parse_args()


async def resolve_target_job_id(*, email: str, requested_job_id: int | None) -> int:
    async with local_session() as session:
        user_result = await session.execute(
            select(User).where(
                User.email == email,
                User.is_deleted.is_(False),
            )
        )
        user = user_result.scalar_one_or_none()
        if user is None:
            raise RuntimeError(f"Candidate user not found for email: {email}")

        query = (
            select(JobProgress)
            .where(
                JobProgress.user_id == user.id,
                JobProgress.current_stage == RecruitmentStage.CONTRACT_POOL.value,
                JobProgress.is_deleted.is_(False),
            )
            .order_by(JobProgress.entered_stage_at.desc(), JobProgress.id.desc())
        )
        if requested_job_id is not None:
            query = query.where(JobProgress.job_id == requested_job_id)

        progress_result = await session.execute(query.limit(1))
        progress = progress_result.scalar_one_or_none()
        if progress is None:
            if requested_job_id is not None:
                raise RuntimeError(
                    f"No contract pool record found for candidate {email} on job {requested_job_id}."
                )
            raise RuntimeError(f"No contract pool record found for candidate {email}.")

        print(
            f"[progress] using job_id={progress.job_id} application_id={progress.application_id} "
            f"job_progress_id={progress.id}"
        )
        return int(progress.job_id)


async def upload_signed_contract(
    client: httpx.AsyncClient,
    *,
    access_token: str,
    job_id: int,
    file_name: str,
    file_bytes: bytes,
) -> dict[str, Any]:
    response = await client.post(
        f"/jobs/{job_id}/signed-contract/upload",
        headers={"Authorization": f"Bearer {access_token}"},
        files={"file": (file_name, file_bytes, "application/pdf")},
    )
    if response.status_code != 201:
        raise RuntimeError(f"Failed to upload signed contract: {response.status_code} {response.text}")
    payload = response.json()
    print(
        f"[upload] job_progress_id={payload['job_progress_id']} "
        f"asset_id={payload['candidate_signed_contract_asset']['id']} "
        f"name={payload['candidate_signed_contract_asset']['original_name']}"
    )
    return payload


async def main() -> None:
    args = parse_args()
    file_bytes = build_demo_pdf_bytes(candidate_email=args.email, note=args.note)
    async with httpx.AsyncClient(base_url=args.base_url, timeout=30.0) as client:
        access_token = await login_candidate(client, email=args.email, password=args.password)
        job_id = await resolve_target_job_id(email=args.email, requested_job_id=args.job_id)
        payload = await upload_signed_contract(
            client,
            access_token=access_token,
            job_id=job_id,
            file_name=args.file_name,
            file_bytes=file_bytes,
        )
        print("[done] signed contract upload completed")
        print(payload)


if __name__ == "__main__":
    asyncio.run(main())
