JOB_STATUS_OPEN = "在招"
JOB_STATUS_PAUSED = "暂停"
JOB_STATUS_CLOSED = "关闭"

JOB_STATUS_OPTIONS = [JOB_STATUS_OPEN, JOB_STATUS_PAUSED, JOB_STATUS_CLOSED]
JOB_WORK_MODE_OPTIONS = ["Remote", "Onsite"]

JOB_DATA_COLLABORATORS_KEY = "collaborators"
JOB_DATA_HIGHLIGHTS_KEY = "highlights"
JOB_DATA_FORM_FIELDS_KEY = "form_fields"
JOB_DATA_AUTOMATION_RULES_KEY = "automation_rules"
JOB_DATA_SCREENING_RULES_KEY = "screening_rules"
JOB_DATA_PUBLISH_CHECKLIST_KEY = "publish_checklist"
JOB_DATA_APPLICATION_SUMMARY_KEY = "application_summary"

