MAIL_TASK_STATUS_MAX_LENGTH = 16
MAIL_TASK_STATUS_PENDING = "pending"
MAIL_TASK_STATUS_RENDERING = "rendering"
MAIL_TASK_STATUS_SENDING = "sending"
MAIL_TASK_STATUS_RETRYING = "retrying"
MAIL_TASK_STATUS_SENT = "sent"
MAIL_TASK_STATUS_FAILED = "failed"

MAIL_TASK_STATUSES = {
    MAIL_TASK_STATUS_PENDING,
    MAIL_TASK_STATUS_RENDERING,
    MAIL_TASK_STATUS_SENDING,
    MAIL_TASK_STATUS_RETRYING,
    MAIL_TASK_STATUS_SENT,
    MAIL_TASK_STATUS_FAILED,
}

MAIL_TASK_DATA_RENDER_CONTEXT_KEY = "render_context"
MAIL_TASK_DATA_RENDERED_CONTEXT_KEY = "rendered_context"
